# Generated by Django 4.2.2 on 2023-06-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plant_type', models.CharField(choices=[('herb', 'Herb'), ('shrub', 'Shrub'), ('perennial', 'Perennial'), ('annual', 'Annual'), ('succulent', 'Succulent'), ('cactus', 'Cactus'), ('water_plant', 'Water Plant')], max_length=20)),
                ('growth_phase', models.CharField(choices=[('seedling', 'Seedling'), ('vegetative_growth', 'Vegetative Growth'), ('flowering', 'Flowering'), ('fruiting', 'Fruiting'), ('dormant', 'Dormant')], max_length=20)),
                ('water_requirement', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('placement', models.CharField(choices=[('indoors', 'Indoors'), ('outdoors', 'Outdoors')], max_length=20)),
            ],
        ),
    ]
