# Generated by Django 4.2.2 on 2023-06-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatedGarden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(choices=[('', 'choose the type of plant'), ('herb', 'Herb'), ('shrub', 'Shrub'), ('perennial', 'Perennial'), ('annual', 'Annual'), ('succulent', 'Succulent'), ('cactus', 'Cactus'), ('water_plant', 'Water Plant')], default='option1', max_length=20),
        ),
    ]
