# Generated by Django 4.2.2 on 2023-06-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatedGarden', '0002_alter_plant_id_alter_plant_plant_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='plant',
            name='growth_phase',
            field=models.CharField(choices=[('', 'Select the growth phase the plant is currently in'), ('seedling', 'Seedling'), ('vegetative_growth', 'Vegetative Growth'), ('flowering', 'Flowering'), ('fruiting', 'Fruiting'), ('dormant', 'Dormant')], default='option1', max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='placement',
            field=models.CharField(choices=[('', 'Select where the plant is placed'), ('indoors', 'Indoors'), ('outdoors', 'Outdoors')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(choices=[('', 'Select the type of plant'), ('herb', 'Herb'), ('shrub', 'Shrub'), ('perennial', 'Perennial'), ('annual', 'Annual'), ('succulent', 'Succulent'), ('cactus', 'Cactus'), ('water_plant', 'Water Plant')], default='option1', max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='water_requirement',
            field=models.CharField(choices=[('', 'Select the level of water requirement'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
    ]
