# Generated by Django 4.2.2 on 2023-06-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatedGarden', '0004_wateringmethod_alter_tank_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilMoistureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
