# Generated by Django 4.2.2 on 2023-06-28 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automatedGarden', '0008_rename_state_pumpstate_is_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lightstate',
            old_name='state',
            new_name='is_on',
        ),
    ]
